### ISSUE TITLE
A fish package manager using bash? Are you serious?

### ISSUE THREAD

**Issue by timofonic** [tuvistavie/fundle#31]
Hello.

I'm researching about different shells and found fish to be really interesting. I'm looking for extra ways to customize it.

I found this "package manager", but got surprised it uses bash instead fish itself. Why?

Kind regards.

**Comment by tuvistavie** [comment]
The package manager itself is written in fish.
bash is only used to setup CI server, and is not needed anywhere else.

**Comment by hauleth** [comment]
GitHub doesn't recognise `.fish` as a source code so it omits it in stats. Or, it recognises it as a `Shell` code (technically correct, the best kind of correct).
